# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
apiVersion: v2
name: lfx-platform
description: LFX Platform v2 Helm chart
type: application
version: 0.3.11
icon: https://github.com/linuxfoundation/lfx-v2-helm/raw/main/img/lfx-logo-color.svg
dependencies:
  - name: traefik
    repository: oci://ghcr.io/traefik/helm
    version: ~36.2.0
    condition: traefik.enabled
  - name: openfga
    repository: https://openfga.github.io/helm-charts
    version: ~0.2.39
    condition: openfga.enabled
  - name: heimdall
    repository: oci://ghcr.io/dadrus/heimdall/chart
    version: ~0.15.8
    condition: heimdall.enabled
  - name: nats
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: ~1.3.8
    condition: nats.enabled
  - name: opensearch
    repository: https://opensearch-project.github.io/helm-charts/
    version: ~2.34.0
    condition: opensearch.enabled
  - name: mailpit
    repository: https://jouve.github.io/charts/
    version: ~0.25.0
    condition: mailpit.enabled
  - name: authelia
    repository: https://charts.authelia.com
    version: ~0.10.41
    condition: authelia.enabled
  - name: nack
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: ~0.29.0
    condition: nack.enabled
  - name: fga-operator
    repository: https://3schwartz.github.io/fga-operator/
    version: ~1.0.0
    condition: fga-operator.enabled
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: ~1.18.2
    condition: cert-manager.enabled
  - name: trust-manager
    repository: https://charts.jetstack.io
    version: ~0.18.0
    condition: trustManagerEnabled
  - name: lfx-v2-query-service
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-query-service/chart
    version: ~0.4.7
    condition: lfx-v2-query-service.enabled
  - name: lfx-v2-project-service
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-project-service/chart
    version: ~0.5.1
    condition: lfx-v2-project-service.enabled
  - name: lfx-v2-fga-sync
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-fga-sync/chart
    version: ~0.2.5
    condition: lfx-v2-fga-sync.enabled
  - name: lfx-v2-access-check
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-access-check/chart
    version: ~0.2.4
    condition: lfx-v2-access-check.enabled
  - name: lfx-v2-indexer-service
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-indexer-service/chart
    version: ~0.4.7
    condition: lfx-v2-indexer-service.enabled
  - name: lfx-v2-committee-service
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-committee-service/chart
    version: ~0.2.10
    condition: lfx-v2-committee-service.enabled
  - name: lfx-v2-meeting-service
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-meeting-service/chart
    version: ~0.5.4
    condition: lfx-v2-meeting-service.enabled
  - name: lfx-v2-auth-service
    repository: oci://ghcr.io/linuxfoundation/lfx-v2-auth-service/chart
    version: ~0.3.1
    condition: lfx-v2-auth-service.enabled
