# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
{{ if and .Values.heimdall.enabled .Values.lfx.generateHeimdallSignerCert.enabled -}}
{{/*
Generate a private key & x509 cert for Heimdall on install of Chart
  TODO: Create RBAC rule to limit secret access to heimdall Pods
*/}}
{{- $heimdallCA := genCAWithKey "heimdall" 365 (genPrivateKey .Values.lfx.generateHeimdallSignerCert.algorithm) -}}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.lfx.generateHeimdallSignerCert.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lfx-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: heimdall
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  "signer.pem": "{{ print $heimdallCA.Key $heimdallCA.Cert | b64enc }}"
{{- end }}
